name: bosh

meta:
  subnet: ~
  security_groups: ~
  db: ~
  default_security_group: ~

# Execute the "bosh status" command to obtain the director_uuid.
director_uuid: (( merge ))

releases:
- name: bosh
  version: 229
- name: bosh-aws-cpi
  version: 36
- name: uaa
  version: latest

compilation:
  workers: 3
  network: default
  reuse_compilation_vms: true
  cloud_properties:
    instance_type: m1.small

update:
  canaries: 1
  canary_watch_time: 3000-120000
  update_watch_time: 3000-120000
  max_in_flight: 4
  max_errors: 1

networks:
  - name: default
    subnets:
      - static:
        - 10.10.1.7 - 10.10.1.10
        cloud_properties:
          subnet: (( meta.subnet ))
          security_groups: (( meta.security_groups ))
        range: 10.10.1.0/24
        reserved: [10.10.1.2-10.10.1.6]
        dns: [10.10.1.6, 10.10.1.2]
        gateway: 10.10.1.1

resource_pools:
  - name: medium
    network: default
    size: 1
    stemcell:
      name: bosh-aws-xen-ubuntu-trusty-go_agent
      version: latest
    cloud_properties:
      instance_type: m1.small

jobs:
  - name: bosh
    templates:
    - {name: nats, release: bosh}
    - {name: redis, release: bosh}
    - {name: blobstore, release: bosh}
    - {name: director, release: bosh}
    - {name: health_monitor, release: bosh}
    - {name: registry, release: bosh}
    - {name: powerdns, release: bosh}
    - {name: aws_cpi, release: bosh-aws-cpi}
    - {name: uaa, release: uaa}
    instances: 1
    resource_pool: medium
    persistent_disk: 100480
    networks:
      - name: default
        static_ips: [10.10.1.7]

properties:
  env:

  postgres: &bosh_db
    adapter: postgres
    port: 5432
    user: (( meta.db.user ))
    password: (( meta.db.pass ))
    host: (( meta.db.host ))
    database: bosh

  dns:
    address: 10.10.1.7
    db: *bosh_db
    user: powerdns
    password: powerdns
    database:
      name: powerdns
    webserver:
      password: powerdns
    replication:
      basic_auth: replication:zxKDUBeCfKYX
      user: replication
      password: powerdns
    recursor: 10.10.1.6

  redis:
    address: 0.bosh.default.bosh.microbosh
    password: redis

  nats:
    address: 0.bosh.default.bosh.microbosh
    user: nats
    password: nats

  director:
    name: bosh
    address: 0.bosh.default.bosh.microbosh
    db: *bosh_db
    ssl: (( merge ))
    user_management:
      provider: uaa
      uaa:
        <<: (( merge ))
        url: "https://10.10.1.7:8443"

  blobstore:
    address: 0.bosh.default.bosh.microbosh
    agent:
      user: agent
      password: agent
    director:
      user: director
      password: director

  registry:
    address: 0.bosh.default.bosh.microbosh
    host: 0.bosh.default.bosh.microbosh
    db: *bosh_db
    http:
      user: registry
      password: registry
      port: 25777
    username: registry
    password: registry
    port: 25777

  hm:
    http:
      user: hm
      password: hm
    director_account:
      user: admin
      password: (( merge ))
      ca_cert: (( merge ))
    event_nats_enabled: false
    email_notifications: false
    tsdb_enabled: false
    pagerduty_enabled: false
    varz_enabled: true

  aws:
    access_key_id: (( merge ))
    secret_access_key: (( merge ))
    default_key_name: bosh
    region: us-east-1
    default_security_groups: [ (( meta.default_security_group )) ]

  agent: {mbus: "nats://nats:nats@10.10.1.7:4222"}
  ntp: &ntp [0.pool.ntp.org, 1.pool.ntp.org]

  uaa:
    <<: (( merge ))
    url: "https://10.10.1.7:8443"
    clients:
      bosh_cli:
        override: true
        authorized-grant-types: password,refresh_token
        # scopes the client may receive
        scope: openid,bosh.admin,bosh.read,bosh.*.admin,bosh.*.read
        authorities: uaa.none
        access-token-validity: 1200 # 10 min
        refresh-token-validity: 86400 # re-login required once a day
        secret: ""

    zones: {internal: {hostnames: []}}

  uaadb: (( merge ))

cloud_provider:
  template: {name: aws_cpi, release: bosh-aws-cpi}
